title: Gensokyo Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.soopy.moe
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems: []
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#7ad0ff"
  enableLastMod: true
  headerTextColor: white
  logo: /img/miku_dispair.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: false
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#e37100"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Critical Services
      description: Services, which if ever goes down for just a minute, will be a
        major pain in the ass for users
      closed: true
    - name: Uncategorized
      untitled: true
  description: >-
    Updated by human(s), for humans.


    For latest and juicy raw uptime status, please visit <a href="https://miku.soopy.moe">miku.soopy.moe</a>.
  enableCustomHTML: false
  useLargeHeaderDesign: false
